# Site
repository: MauricioCantoSosa/MauricioCantoSosa.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mauricio Canto Sosa
title: Machine Learning Engineer
email: maucs98@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number
# phone_title: Phone (Phone title override)
# website: Your website
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  MauricioCantoSosa
# stackoverflow_username: "00000001"
linkedin_username: mauriciocantososa

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mauricio Canto, I’m a budding Machine Learning Engineer who is passionate about learning new stuff every day. 
  My insightfulness and dedication that I put into my work make me perfect for working with Data. Each situation requires different solutions,
  my mission is to find the best one.

  I started programming when I was in university and now, I cannot stop, clocking thousands of hours coding.
  I enjoy working with data and creating ML algorithms that can extract meaning out of it. 
  I have worked with a range of different languages and libraries, and I am always looking for opportunities to work with something new. 
  The things that I currently have the most experience with are: <mark>Python</mark>,  <mark>PyTorch</mark>, <mark>TensorFlow</mark>, <mark>Scikit-Learn</mark>, <mark>SQL</mark>,
  <mark> AWS</mark>,  <mark>PowerBI</mark> and <mark>Git</mark>.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Stock Trend Prediction and Analysis
        link: https://github.com/MauricioCantoSosa/DSAC-FG-MVP
        link_text: Link to Project
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/MauricioCantoSosa/DSAC-FG-MVP
        quote: >
          Yes, the cliché stock prediction project, but with a bit more effort.

        description: | # this will include new lines to allow paragraphs
          A simple webpage built using <mark>Streamlit</mark> to display the desired stock price over time along with a few <mark>Time Series Forecasts and Analysis</mark>.
          An <mark>LSTM</mark> forecast architected using <mark>TensorFlow</mark>, a <mark>SARIMAX</mark> forecast using <mark>skforecast</mark>, and finally a forecast with
          an additive regression model using <mark>Prophet</mark>. Some plots represent the Prophet’s model trend, seasonality and  holiday effects.

          The data from the project was retrieved using Yahoo Finance <mark>API</mark> and then stored in an <mark>AWS S3</mark> bucket to be retrieved if the same stock was needed on
          another time (A little redundant, but I wanted more experience with AWS). After the data was retrieved the forecasts and analysis were made and displayed in a dashboard-like
          webpage hosted with Streamlit. 

          The whole project was designed and written using <mark>OOP</mark> principles, and <mark>documented</mark> following <mark>PEP</mark> guidelines.
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Wikipedia Answering Chat-GPT
        link: https://github.com/MauricioCantoSosa/Wikipedia-Answering-Bot
        link_text: Link to Project
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/MauricioCantoSosa/Wikipedia-Answering-Bot
        quote: >
          A custom knowledge <mark>LLM</mark>, powered by OpenAI.
        description: | # this will include new lines to allow paragraphs
          A Chat-bot that can answer any question from any Wikipedia article.
          The application uses <mark>Langchain</mark> to get OpenAI <mark>Embeddings</mark>, and access the <mark>Vector Database</mark> <mark>Pinecone</mark>.
          The user is  prompted to enter the title of any Wikipedia article  and a question to get answered from information retrieved from the selected article.
          The Wikipedia article is chunked into smaller documents using Langchain’s recursive character splitter with the same size.
          The documents are stored into Pinecone as embeddings and a similarity search is performed  to determine which chunks of text are more suitable to answer
          the user’s question and provide the text with the answer. 

          Although the project is simple and the user has to provide the “custom knowledge” to the application, the idea has potential if
          embeddings are created from the right information. It could be used by a company to create their own proprietary chatbot for employees
          or partners to get quick information about certain private company information. It could also be potentially used to create domain expert
          LLM’s that could help professionals do certain types of jobs faster (e.g. a chatbot with expertise in HP Laptops).

      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Emotion Recognition
        link: https://github.com/MauricioCantoSosa/Machine-Learning-Algorithms-for-Image-Emotion-Classification
        link_text: Link to Project
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/MauricioCantoSosa/Machine-Learning-Algorithms-for-Image-Emotion-Classification
        description: | # this will include new lines to allow paragraphs
          This project’s purpose was to explore the capabilities of different <mark>Machine Learning</mark> classification algorithms to assign the correct
          displayed emotion on each picture on a face image dataset.

          The ML models were architected using <mark>Scikit-Learn</mark>. In the notebook comparisons were made performing principal component analysis (<mark>PCA</mark>),
          linear discriminant analysis (<mark>LDA</mark>), and no dimensionality reduction methods. The ML algorithms used were <mark>Naïve Bayes</mark>, <mark>Logistic Regression</mark>,
          Support Vector Machine (<mark>SVM</mark>). All the combinations of algorithms and dimensionality reduction methods were compared to localize the one with the best results for the task,
          as well as explore the reasons why some combinations worked and did not work well.

          The task would have been better performed by a <mark>Neural Network</mark>, but the purpose of the project was to explore certain ML algorithms and understand their strengths and weaknesses.

      - layout: top-middle
        title: Check out my Github to see the rest of my projects.
        link: https://github.com/MauricioCantoSosa
        link_text: Github Link
        description: | # this will include new lines to allow paragraphs
          Here I just included some of my best projects (in my opinion), be sure to check out my <a href="https://github.com/MauricioCantoSosa">Github</a> to see the rest of my work.
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: The Big Neural Data Project
        sub_title: Data Science Intern
        caption: May 2020 - Apr 2021
        description: | # this will include new lines to allow paragraphs
          - Assisted in scientific research on behavioral decision making changes based on induced negative biases, and analyzed the
          results.
          
          - Designed and implemented dozens of machine learning and deep learning models to provide diagnostic analytics to
          medical professionals.
          
          - Analyzed datasets and created dashboards to communicate insights and to assist with data driven decision-making.

      - layout: left
        title: The Big Neural Data Project
        sub_title: Data Science Intern
        caption: Jan 2019 - Dec 2019
        description: | # this will include new lines to allow paragraphs
          -  Built the architecture of an SQL database and implemented a data pipeline to retrieve and store data from a Unity based
             project, saving an approximate of 30 hours of monthly labor.

          
          - Performed EDA and created dashboards for project proposals and addressing business problems.
          
          - Designed and implemented multiple machine learning models for structured and semi-structured data to perform both
            descriptive and predictive analytics.

          
  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: Lambton College
        sub_title: Graduate Degree in Artificial Intelligence and Machine Learning
        caption: Jan 2022 - Aug 2023
        description: | # this will include new lines to allow paragraphs
          During my time at Lambton College, I deeply explored the theoretical side of a plethora of <mark>Machine Learning</mark>
          and <mark>Deep Learning</mark> algorithms, as well as learned how to apply them to real problems and data using <mark>Python</mark>.
          Some of my courses deviated from the technical side of things and emphasized the business side of Machine Learning (when is it useful, the cost of it, laws, etc). 
          
          I developed a lot of projects during my time at Lambton, both coursework and Personal, some of these projects were just <mark>Jupyter notebooks</mark>,
          and many of them end-to-end projects resembling a real product. Some of the most important skills I learned in Lambton were how to do research in the market
          you’re working on, and replicating algorithms and methods found in state-of-the-art research papers.

          Some of the courses I took (apart from the obvious Machine Learning ones) were: Big Data Fundamental Storage, Data Visualization, Natural Language Processing,
          Data Mining and Analysis, and Social Media Analytics. I also made it to the Dean’s Honour list for two of the three semester I was eligible for it.
          
          <mark>GPA 3.54 / 4</mark>

      - layout: left
        title: Universidad Politécnica de Yucatán
        sub_title: BSc Embedded Systems Engineering
        caption: Aug 2017 - May 2021
        description: | # this will include new lines to allow paragraphs
          Description In Progress.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have not taken the time to write more about myself on this section, but I will soon. Or maybe I'll just changed this and add a skills sections, who knows.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
